### ISSUE TITLE
Convention

### ISSUE THREAD

**Issue by ajbraus** [dy-fi/Giphy-Search#1]
Hey there a few things to clean up here:

1. Make sure your app.js has four parts in this order: declarations, initialization of middleware, routes, intialization of server.
1. Make sure your app works without a search term using one of the patterns I showed or your colleagues discovered.

Please complete these changes to get credit.

**Comment by dy-fi** [comment]
I reorganized the file and now works without a query, instead replacing it with the top trending gifs.
